// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Summarizes student feedback to quickly understand key points.
 *
 * - summarizeStudentFeedback - A function that handles the summarization of student feedback.
 * - SummarizeStudentFeedbackInput - The input type for the summarizeStudentFeedback function.
 * - SummarizeStudentFeedbackOutput - The return type for the summarizeStudentFeedback function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SummarizeStudentFeedbackInputSchema = z.object({
  feedback: z
    .string()
    .describe('The student feedback to be summarized.'),
});
export type SummarizeStudentFeedbackInput = z.infer<typeof SummarizeStudentFeedbackInputSchema>;

const SummarizeStudentFeedbackOutputSchema = z.object({
  summary: z.string().describe('The summarized feedback.'),
});
export type SummarizeStudentFeedbackOutput = z.infer<typeof SummarizeStudentFeedbackOutputSchema>;

export async function summarizeStudentFeedback(input: SummarizeStudentFeedbackInput): Promise<SummarizeStudentFeedbackOutput> {
  return summarizeStudentFeedbackFlow(input);
}

const summarizeStudentFeedbackPrompt = ai.definePrompt({
  name: 'summarizeStudentFeedbackPrompt',
  input: {schema: SummarizeStudentFeedbackInputSchema},
  output: {schema: SummarizeStudentFeedbackOutputSchema},
  prompt: `Summarize the following student feedback, removing unnecessary pleasantries, apologies, or overly informal phrasing. Focus on the key points and suggestions provided by the student.\n\nFeedback: {{{feedback}}}`,
});

const summarizeStudentFeedbackFlow = ai.defineFlow(
  {
    name: 'summarizeStudentFeedbackFlow',
    inputSchema: SummarizeStudentFeedbackInputSchema,
    outputSchema: SummarizeStudentFeedbackOutputSchema,
  },
  async input => {
    const {output} = await summarizeStudentFeedbackPrompt(input);
    return output!;
  }
);
